# This file was generated by GoReleaser. DO NOT EDIT.
cask "glean" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "b0804fdb818201cbe874e8298feba6d95225f1d9acb62430172644573b5bbdee"
      url "https://github.com/amalucelli/glean/releases/download/v#{version}/glean_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3bd126a50cbf799c775b1b013620fc29ec7ff1b21fa55a75fe0648fad69d2f25"
      url "https://github.com/amalucelli/glean/releases/download/v#{version}/glean_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7c8c8d7e9e8f1ce0f0bf0050fd2e864a4e016a69826a19d1b7539b03ad80fef4"
      url "https://github.com/amalucelli/glean/releases/download/v#{version}/glean_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e9d41ccb34521738308ec05107c160f610e5e8cbc0d6c54fd4b246a90d047625"
      url "https://github.com/amalucelli/glean/releases/download/v#{version}/glean_#{version}_linux_amd64.tar.gz"
    end
  end

  name "glean"
  desc "Track which files changed since a tool last processed them — incremental work for loops, CI, and agents."
  homepage "https://github.com/amalucelli/glean"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glean"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/glean"]
    end
  end

  # No zap stanza required
end
