# This file was generated by GoReleaser. DO NOT EDIT.
cask "glean" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "f078a0209067816cfe765507892e4a1b392e320d6076b39a913177bc80ebd0fb"
      url "https://github.com/amalucelli/glean/releases/download/v#{version}/glean_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0caf479611623de48994b26296cf4232b7a775458a943e4bb54341366dbe8fc7"
      url "https://github.com/amalucelli/glean/releases/download/v#{version}/glean_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d108ffa3f8e5ad4e9ff51388f092f8f7b46f34812ee6593a99639b270dd8a1a1"
      url "https://github.com/amalucelli/glean/releases/download/v#{version}/glean_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "77498f6421321b931080ef383afe5ee2099189a319ddcf59a1be0e77b264b8bc"
      url "https://github.com/amalucelli/glean/releases/download/v#{version}/glean_#{version}_linux_amd64.tar.gz"
    end
  end

  name "glean"
  desc "Track which files changed since a tool last processed them — incremental work for loops, CI, and agents."
  homepage "https://github.com/amalucelli/glean"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glean"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/glean"]
    end
  end

  # No zap stanza required
end
