# This file was generated by GoReleaser. DO NOT EDIT.
cask "glean" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "7c7b1e07c288f6c7bd5073492fdb6c6cd79be0f6b80cd1ba8e9a1d8ab54285e3"
      url "https://github.com/amalucelli/glean/releases/download/v#{version}/glean_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bdf394675401d93ec87e504f8ac7b092c46890fd7bf703d859ece5951e1871ef"
      url "https://github.com/amalucelli/glean/releases/download/v#{version}/glean_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "84cd6da55a01e1a76f59d14823f61ffc8fa763f1586b75f8b805d396acf2e8b2"
      url "https://github.com/amalucelli/glean/releases/download/v#{version}/glean_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7817892731a266d6a73a4cb9531c196ec177bb11d4ee8a6dfe6acbb7e3f675fc"
      url "https://github.com/amalucelli/glean/releases/download/v#{version}/glean_#{version}_linux_amd64.tar.gz"
    end
  end

  name "glean"
  desc "Track which files changed since a tool last processed them — incremental work for loops, CI, and agents."
  homepage "https://github.com/amalucelli/glean"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glean"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/glean"]
    end
  end

  # No zap stanza required
end
