# This file was generated by GoReleaser. DO NOT EDIT.
cask "statusline" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "f7350af642e1425fb6f9987e802707bc6ebbbfe5b454bfc65a0373f623ff784e"
      url "https://github.com/amalucelli/statusline/releases/download/v#{version}/statusline_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9d821ff211c2d5dfbb4a6a10838edb65582c169489bdb27e011c9d12baf8f858"
      url "https://github.com/amalucelli/statusline/releases/download/v#{version}/statusline_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dd2014a6bc9f39968d4cc69b36879bf290c812e1e1b97189ad0b88c8d8e245a4"
      url "https://github.com/amalucelli/statusline/releases/download/v#{version}/statusline_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f5e0579af51c54f1c3f84ed21d7d140b9fea4483a54a8f2ffd22ae8c34eb9aa6"
      url "https://github.com/amalucelli/statusline/releases/download/v#{version}/statusline_#{version}_linux_amd64.tar.gz"
    end
  end

  name "statusline"
  desc "A status line for Claude Code — model, context, session time, token counts, and usage limits."
  homepage "https://github.com/amalucelli/statusline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "statusline"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/statusline"]
    end
  end

  # No zap stanza required
end
