# This file was generated by GoReleaser. DO NOT EDIT.
cask "statusline" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "738201e741331a6b9e8cb48947a20bee65f017e3f61857d7f9bc6b2f32615f87"
      url "https://github.com/amalucelli/statusline/releases/download/v#{version}/statusline_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6d678133c6bac3c62a098107097a126f4244953f248b32f899491623191c791b"
      url "https://github.com/amalucelli/statusline/releases/download/v#{version}/statusline_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cc212191b10e51f2f557134c2b8439e2cd9f8b2fd3179b13d300b50dec12db35"
      url "https://github.com/amalucelli/statusline/releases/download/v#{version}/statusline_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3c7563a8cdd3c8c86357adb77fdfbb04f250743abe90e1d22fe42bab0efc4b9d"
      url "https://github.com/amalucelli/statusline/releases/download/v#{version}/statusline_#{version}_linux_amd64.tar.gz"
    end
  end

  name "statusline"
  desc "A status line for Claude Code — model, context, session time, token counts, and usage limits."
  homepage "https://github.com/amalucelli/statusline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "statusline"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/statusline"]
    end
  end

  # No zap stanza required
end
