# This file was generated by GoReleaser. DO NOT EDIT.
cask "statusline" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "df3e12a12d975b859c07c7efb15d5d2a50f0b051f20a81a93655ac28294a2fdb"
      url "https://github.com/amalucelli/statusline/releases/download/v#{version}/statusline_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "04eb8e14c0a55c4d920c322798959019bc7ca325bd95b214d1d46ff5990ab802"
      url "https://github.com/amalucelli/statusline/releases/download/v#{version}/statusline_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "902c7881827207df19bbae3e8ea7664f75b34d377c5bb817c5d68d1c7f669329"
      url "https://github.com/amalucelli/statusline/releases/download/v#{version}/statusline_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5846ab280bdf07622cf01ce0730da88b951e1f2b49a4b7acda4ac0294643db24"
      url "https://github.com/amalucelli/statusline/releases/download/v#{version}/statusline_#{version}_linux_amd64.tar.gz"
    end
  end

  name "statusline"
  desc "A status line for Claude Code — model, context, session time, token counts, and usage limits."
  homepage "https://github.com/amalucelli/statusline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "statusline"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/statusline"]
    end
  end

  # No zap stanza required
end
