# This file was generated by GoReleaser. DO NOT EDIT.
cask "steer" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "c955d8f977016d65ccc560ef9b934775444417bf37dcf5d4f9f16632b3111834"
      url "https://github.com/amalucelli/steer/releases/download/v#{version}/steer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7515203ae76590bc07a3fcdef80c0241f8fdf9e590f1b970526af732d1f84467"
      url "https://github.com/amalucelli/steer/releases/download/v#{version}/steer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c738a1e5be5e4e96a4c17882a855787fb3a5354d59b2e0b28bee1415b0dd5b52"
      url "https://github.com/amalucelli/steer/releases/download/v#{version}/steer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4ccc6fd25505a73377b390b28a03e4b65145bccd715dbc21a1707979a436e9aa"
      url "https://github.com/amalucelli/steer/releases/download/v#{version}/steer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "steer"
  desc "A Claude Code and Codex hook that steers tool calls toward the right tool — a configurable rule engine over shell-aware payloads."
  homepage "https://github.com/amalucelli/steer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "steer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/steer"]
    end
  end

  # No zap stanza required
end
