# This file was generated by GoReleaser. DO NOT EDIT.
cask "steer" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "4fa4d424b56a0f1386ffe8de69b6ac397083d5b5e481df8e4d9f101dc210ecb0"
      url "https://github.com/amalucelli/steer/releases/download/v#{version}/steer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ffa434d81608b4407d781d6c57805e5b0de1789e30d0fa9e79caf0a71fc3d677"
      url "https://github.com/amalucelli/steer/releases/download/v#{version}/steer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "513f344fcd9e9f252ee10d106ba9730e540d0e4505b67224acb5fb019b6e50bc"
      url "https://github.com/amalucelli/steer/releases/download/v#{version}/steer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "93b056d76696faa1af0642bc438957bcc7030238fa283a2f2d26bc1d7b79e31d"
      url "https://github.com/amalucelli/steer/releases/download/v#{version}/steer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "steer"
  desc "A Claude Code hook that steers tool calls toward the right tool — a configurable rule engine over shell-aware payloads."
  homepage "https://github.com/amalucelli/steer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "steer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/steer"]
    end
  end

  # No zap stanza required
end
