# This file was generated by GoReleaser. DO NOT EDIT.
cask "steer" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "a0e80792861db1eedaf3b55d4a3ab06df84c07be7be0e24689cef764a41a51a4"
      url "https://github.com/amalucelli/steer/releases/download/v#{version}/steer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9b4a36f3c22a7e8297f06da55b011fa12e2fea14a8a47c3b7c4e8800bced0ad8"
      url "https://github.com/amalucelli/steer/releases/download/v#{version}/steer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fd1289aeaddd3708f37d5af59ba33187eb688de1775151a9e48c39d56722a79f"
      url "https://github.com/amalucelli/steer/releases/download/v#{version}/steer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0f581c8a24d8b26ddb8271e2eddb8208e5437fb74b1c37bbceb3c2e404a79240"
      url "https://github.com/amalucelli/steer/releases/download/v#{version}/steer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "steer"
  desc "A Claude Code and Codex hook that steers tool calls toward the right tool — a configurable rule engine over shell-aware payloads."
  homepage "https://github.com/amalucelli/steer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "steer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/steer"]
    end
  end

  # No zap stanza required
end
